// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextLIMS.DAL.Data;

#nullable disable

namespace NextLIMS.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614210957_seeding_UserSeeder")]
    partial class seeding_UserSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SampleId")
                        .HasColumnType("int");

                    b.Property<int?>("SampleTestId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.HasIndex("SampleTestId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("NID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TenantId", "NID")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.ConfirmationTestTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmationTestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TestId");

                    b.ToTable("ConfirmationTestTemplates");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.DetectionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnrichmentMedia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MediaAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SampleTestId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SampleTestId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("DetectionData");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.EnumerationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiluentAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SampleTestId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SampleTestId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("EnumerationData");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.EnumerationDilution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColonyCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DilutionOrVolume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DilutionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnumerationDataId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelectedForCalculation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("VolumePlated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EnumerationDataId");

                    b.HasIndex("TenantId");

                    b.ToTable("EnumerationDilutions");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("passwordResets");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Allows retrieving the list of all available permissions in the system",
                            Name = "GET_ALL_Permissions"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Allows creating a new role",
                            Name = "CreateRole"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Allows retrieving the list of all roles",
                            Name = "GetRoles"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Allows assigning one or more permissions to a role",
                            Name = "Add_Permissions_to_Role"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Allows removing a specific permission from a user",
                            Name = "Remove_Permission_from_User"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Allows sending an invitation to a new employee to join the lab",
                            Name = "Invite_employee"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Allows retrieving the list of employees belonging to a specific lab",
                            Name = "GetEmployeesByLab"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Allows creating a new sample record",
                            Name = "CreateSample"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Allows retrieving the list of all samples",
                            Name = "GetAllSamples"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Allows retrieving a sample along with its associated tests",
                            Name = "GetSampleWithItsTests"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Allows linking a sample to a specific test",
                            Name = "Add_Sample_To_Test"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Allows removing a sample from a specific test",
                            Name = "Remove_Sample_From_Test"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Allows filtering samples by sample ID or client ID",
                            Name = "Filter_Samples_by_sampleId_OR_ClientId"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Allows filtering samples by their current status",
                            Name = "Filter_Samples_by_Status"
                        });
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TenantId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 9, 57, 343, DateTimeKind.Local).AddTicks(8544),
                            Description = "Has full access to lab configuration, settings, users, and system management",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 9, 57, 343, DateTimeKind.Local).AddTicks(8594),
                            Description = "Can view and log samples into the system",
                            IsActive = true,
                            Name = "Receptionist"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 9, 57, 343, DateTimeKind.Local).AddTicks(8597),
                            Description = "Performs the first step of laboratory tests",
                            IsActive = true,
                            Name = "Analyst"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 9, 57, 343, DateTimeKind.Local).AddTicks(8599),
                            Description = "Enters enumeration colony counts, records detection results (P/N), performs confirmation tests, performs advanced molecular tests, and requests retests",
                            IsActive = true,
                            Name = "Senior Analyst"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 9, 57, 343, DateTimeKind.Local).AddTicks(8601),
                            Description = "Approves test results, authorizes retests, and reassigns tasks",
                            IsActive = true,
                            Name = "Department Director"
                        });
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("GrantedBy")
                        .HasColumnType("int");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrantedBy");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasFilter("[RoleId] IS NOT NULL AND [PermissionId] IS NOT NULL");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 19,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 22,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 23,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 14,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 24,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 9,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 25,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 10,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 26,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 11,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 27,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 12,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 28,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 14,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 29,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 3,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 30,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 7,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 31,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 9,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 32,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 10,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 33,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 12,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 34,
                            GrantedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 14,
                            RoleId = 5
                        });
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("SampleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.SampleConfirmationTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmationTestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePerformed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("PerformedBySeniorAnalystId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleTestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformedBySeniorAnalystId");

                    b.HasIndex("SampleTestId");

                    b.ToTable("SampleConfirmationTests");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.SampleTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SampleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantTestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SampleId");

                    b.HasIndex("TenantTestId");

                    b.ToTable("SampleTests");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.SampleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SampleTypes");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.SampleWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("SampleId");

                    b.HasIndex("TenantId");

                    b.ToTable("SampleWorkflows");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MonthlySampleLimit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SamplesUsedThisMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("SubscriptionEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SubscriptionStartDate")
                        .HasColumnType("date");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.TenantDepartment", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("TenantId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TenantDepartments");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.TenantTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StandardMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int?>("TurnaroundTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TestId");

                    b.HasIndex("TenantId", "TestId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("TenantTests");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.TenantTestSampleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TenantTestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SampleTypeId");

                    b.HasIndex("TenantTestId", "SampleTypeId")
                        .IsUnique();

                    b.ToTable("TenantTestSampleTypes");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("StandardMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TurnaroundTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TenantId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.TestSampleType", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("SampleTypeId")
                        .HasColumnType("int");

                    b.HasKey("TestId", "SampleTypeId");

                    b.HasIndex("SampleTypeId");

                    b.ToTable("TestSampleTypes");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed.hassan@labtest.com",
                            IsActive = true,
                            Name = "Ahmed Hassan",
                            PasswordHash = "$2b$12$Qe1daAScKU/Vt97doG0Y4.UU7kgptQzPFovBjfUucyRm/scg3sYDW",
                            RoleId = 1,
                            TenantId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mona.khaled@labtest.com",
                            IsActive = true,
                            Name = "Mona Khaled",
                            PasswordHash = "$2b$12$Qe1daAScKU/Vt97doG0Y4.UU7kgptQzPFovBjfUucyRm/scg3sYDW",
                            RoleId = 2,
                            TenantId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "youssef.adel@labtest.com",
                            IsActive = true,
                            Name = "Youssef Adel",
                            PasswordHash = "$2b$12$Qe1daAScKU/Vt97doG0Y4.UU7kgptQzPFovBjfUucyRm/scg3sYDW",
                            RoleId = 3,
                            TenantId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.mostafa@labtest.com",
                            IsActive = true,
                            Name = "Sara Mostafa",
                            PasswordHash = "$2b$12$Qe1daAScKU/Vt97doG0Y4.UU7kgptQzPFovBjfUucyRm/scg3sYDW",
                            RoleId = 4,
                            TenantId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "khaled.ibrahim@labtest.com",
                            IsActive = true,
                            Name = "Khaled Ibrahim",
                            PasswordHash = "$2b$12$Qe1daAScKU/Vt97doG0Y4.UU7kgptQzPFovBjfUucyRm/scg3sYDW",
                            RoleId = 5,
                            TenantId = 3
                        });
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.AuditLog", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Sample", "Sample")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextLIMS.DAL.Data.Models.SampleTest", "SampleTest")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SampleTestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sample");

                    b.Navigation("SampleTest");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Client", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany("Clients")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.ConfirmationTestTemplate", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextLIMS.DAL.Data.Models.Test", "Test")
                        .WithMany("ConfirmationTestTemplates")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.DetectionData", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.SampleTest", "SampleTest")
                        .WithOne("DetectionData")
                        .HasForeignKey("NextLIMS.DAL.Data.Models.DetectionData", "SampleTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SampleTest");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.EnumerationData", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.SampleTest", "SampleTest")
                        .WithOne("EnumerationData")
                        .HasForeignKey("NextLIMS.DAL.Data.Models.EnumerationData", "SampleTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SampleTest");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.EnumerationDilution", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.EnumerationData", "EnumerationData")
                        .WithMany("EnumerationDilutions")
                        .HasForeignKey("EnumerationDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnumerationData");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.PasswordReset", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Role", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.RolePermission", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextLIMS.DAL.Data.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Sample", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Client", "Client")
                        .WithMany("Samples")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany("Samples")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.SampleConfirmationTest", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.User", "PerformedBySeniorAnalyst")
                        .WithMany()
                        .HasForeignKey("PerformedBySeniorAnalystId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.SampleTest", "SampleTest")
                        .WithMany("SampleConfirmationTests")
                        .HasForeignKey("SampleTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedBySeniorAnalyst");

                    b.Navigation("SampleTest");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.SampleTest", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextLIMS.DAL.Data.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextLIMS.DAL.Data.Models.Sample", "Sample")
                        .WithMany("SampleTests")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextLIMS.DAL.Data.Models.TenantTest", "TenantTest")
                        .WithMany("SampleTests")
                        .HasForeignKey("TenantTestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Sample");

                    b.Navigation("TenantTest");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.SampleWorkflow", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextLIMS.DAL.Data.Models.Sample", "Sample")
                        .WithMany("SampleWorkflows")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany("SampleWorkflows")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Sample");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.TenantDepartment", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Department", "Department")
                        .WithMany("TenantDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany("TenantDepartments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.TenantTest", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany("TenantTests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NextLIMS.DAL.Data.Models.Test", "Test")
                        .WithMany("TenantTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.TenantTestSampleType", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.SampleType", "SampleType")
                        .WithMany("TenantTestSampleTypes")
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.TenantTest", "TenantTest")
                        .WithMany("TenantTestSampleTypes")
                        .HasForeignKey("TenantTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SampleType");

                    b.Navigation("TenantTest");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Test", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Department", "Department")
                        .WithMany("Tests")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Department");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.TestSampleType", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.SampleType", "SampleType")
                        .WithMany("TestSampleTypes")
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.Test", "Test")
                        .WithMany("TestSampleTypes")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SampleType");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.User", b =>
                {
                    b.HasOne("NextLIMS.DAL.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextLIMS.DAL.Data.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Client", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Department", b =>
                {
                    b.Navigation("TenantDepartments");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.EnumerationData", b =>
                {
                    b.Navigation("EnumerationDilutions");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Sample", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("SampleTests");

                    b.Navigation("SampleWorkflows");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.SampleTest", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("DetectionData");

                    b.Navigation("EnumerationData");

                    b.Navigation("SampleConfirmationTests");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.SampleType", b =>
                {
                    b.Navigation("TenantTestSampleTypes");

                    b.Navigation("TestSampleTypes");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Tenant", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Clients");

                    b.Navigation("Roles");

                    b.Navigation("SampleWorkflows");

                    b.Navigation("Samples");

                    b.Navigation("TenantDepartments");

                    b.Navigation("TenantTests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.TenantTest", b =>
                {
                    b.Navigation("SampleTests");

                    b.Navigation("TenantTestSampleTypes");
                });

            modelBuilder.Entity("NextLIMS.DAL.Data.Models.Test", b =>
                {
                    b.Navigation("ConfirmationTestTemplates");

                    b.Navigation("TenantTests");

                    b.Navigation("TestSampleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
